services:

  redis:
    image: redis:latest
    command: ["redis-server", "--save", "", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    networks:
      - container_network

  backend: # Django
    build: library:latest
    ports:
      - "8000:8000"
    networks:
      - container_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - sqlite_db:/app

networks:
  container_network:
    driver: bridge

volumes:
  sqlite_db: