services:

  redis:
    image: redis:latest
    command: ["redis-server", "--save", "", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    networks:
      - container_network

  backend: # Django
    build: .
    ports:
      - "8000:8000"
    networks:
      - container_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - container_network

networks:
  container_network:
    driver: bridge
