services:

  redis:
    image: redis:latest
    command: ["redis-server", "--save", "", "--loglevel", "warning"]
    ports:
      - "6379:6379"
    networks:
      - container_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 10s
      retries: 1
      start_period: 10s

  backend:
    image: "${BACKEND_IMAGE}"
    ports:
      - "8000:8000"
    env_file:
      - ".env"
    networks:
      - container_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/api/v1/common/health-check || exit 1
      interval: 10s
      timeout: 10s
      retries: 1
      start_period: 10s

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
    networks:
      - container_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - container_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - container_network

networks:
  container_network:
    driver: bridge
